### ISSUE TITLE
Config rubocop

### ISSUE THREAD

**Issue by xjb** [xjb/rails-sandbox#53]
```yaml
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
```

**Comment by xjb** [comment]
exclude .*

**Comment by xjb** [comment]
```yaml
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: never
```
